# Generated by Django 6.1.1 on 2026-09-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('hora', models.TimeField(verbose_name='Hora del Evento')),
                ('lugar', models.CharField(max_length=255, verbose_name='Lugar / Recinto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen (archivo)')),
                ('imagen_url', models.URLField(blank=True, help_text='Enlace a imagen externa si no subes un archivo', null=True, verbose_name='URL de Imagen (opcional)')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base ($)')),
                ('cupo_total', models.PositiveIntegerField(verbose_name='Cupo Total')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('comprador', 'Comprador'), ('organizador', 'Organizador')], default='comprador', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='TipoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: General, VIP, Platea', max_length=100, verbose_name='Nombre del Ticket')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('cantidad_total', models.PositiveIntegerField(default=0, verbose_name='Cupo Asignado')),
                ('cantidad_disponible', models.PositiveIntegerField(verbose_name='Cantidad Disponible')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ticket', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Ticket',
                'verbose_name_plural': 'Tipos de Ticket',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario ($)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total ($)')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('codigo_ticket', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Código Único de Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('tipo_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='eventos.tipoticket', verbose_name='Tipo de Ticket')),
            ],
            options={
                'verbose_name': 'Compra de Ticket',
                'verbose_name_plural': 'Compras de Tickets',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
